- _posts/blog/2016-08-23-abstractions-session-1.md
+ First post on github pages. 
+ Post on elixir session of abstractions.
+ Ensured links open in new tabs
+ Created top section specifying layout, tags, etc.
+ Good post to use as a template for future posts as I transition to github pages
> Abstractions Post 1

- _posts/blog/2016-08-25-abstractions-dancing-data.md
+ Added summary of dancing with data session.
> Dancing with Data write-up

- _posts/blog/2016-08-25-abstractions-ordinary-people.md
- _posts/blog/2016-08-26-abstractions-get-a-whiff.md
+ Writeup of sandi's talk 
+ Update to ordinary people because silly stylized quotes mess up markdown.
> Summary of Sandi's whiff talk

- _posts/blog/2016-08-26-abstractions-optimizations.md
+ summary of aaron patterson's optimization talk.
> Optimizations talk write-up

- _posts/blog/2016-08-26-bstractions-twelve-factor-container.md
+ Casey West's twelve factor talk summary
> Twelve-Factor container talk write up

- _config.yml
+ Added commenting ability via disqus
> Disqus commenting ability

- _posts/blog/2016-08-31-abstractions-npm-past-present-future.md
> Abstractions NPM keynote

- _posts/blog/2016-08-31-abstractions-lucky.md
+ Write up and reflection thoughts on lucky talk.
> Abstractions Lucky Summary

- _posts/blog/2016-09-01-abstractions-culture-of-learning.md
+ Joe's talk on learning write up
> Abstractions Learning Culture write-up

- _posts/blog/2016-09-01-abstractions-pull-requests.md
+ Write up on Sean's pull request talk.
> Abstractions Pull Requests

- _posts/blog/2016-09-01-abstractions-code-hospitality.md
+ Nadia's code hospitality write up.
> Abstractions Code Hospitality

- _posts/blog/2016-09-10-github-pages-small-hints.md
+ Gives hints about blogger importing
+ Covers url redirects to purchased domain
> Github pages starter hints

- _posts/blog/2016-09-24-strangeloop-2016-summary.md
+ write up of strangeloop conference 2016.
> Strangeloop 2016: A Summary

- _posts/blog/2016-10-15-upcoming-talks.md
> Upcoming speaking

- _posts/blog/2016-11-13-childcare-at-tech-conferences.md
+ Connecting people to childcare posts
> childcare posts

- _posts/blog/2016-01-13-interesting-reads.md
- _posts/blog/2016-11-13-childcare-at-tech-conferences.md
> Interesting posts

- _data/navigation.yml
- about/index.md
- speaking/index.md
+ Updates speaking section
+ Updates About me section
> General updates

- _data/navigation.yml
- _sass/_search.scss
- search/index.md
Adds google search. Not the prettiest but it'll do.
> Adds Search

- _posts/blog/2017-01-28-first-they-came.md
a tough piece to write about my feelings related to the world right now
> First they came piece

- _posts/blog/2017-02-01-hack-your-workday-p1.md
> hack your workday part 1

- _posts/blog/2017-02-05-hack-your-workday-p2.md
+ adding action steps to your goals
+ find people to keep you accountable 
TODO: link to part 1
in part 1, link to part 2
> Hack your workday part 2

- _posts/blog/2016-01-15-leadership-in-stickers.md
Blog post outlining a leadership workshop that can be run using stickers
> Leadership Workshop- leadership profile in stickers

- _data/navigation.yml
- _includes/email-list.html
- blog/index.html
- index.html
- newsletter/index.html
Added email signup to the site.
In case I need to revisit this in the future [this link](http://www.controlfd.com/2016/05/16/add-a-mailchimp-subscriber-form-to-your-jekyll-blog.html) was very helpful and clear.
> Add email signup

- _posts/blog/2017-02-22-workshops-for-engineers-part-3.md
- _posts/blog/2017-06-04-workshops-for-engineers-part-3.md
conclusion, supporting materials, and materials needed
> workshop for engineers part 3

- _posts/blog/2017-03-05-getting-feedback.md
- _posts/blog/2017-06-25-getting-feedback.md
focused on just some questions to ask people on your team
> short blog post on getting feedback

- _posts/blog/2017-03-01-leadership-as-a-drawing-workshop.md
+ workshop writeup on drawing yourself as a leader
> Leadership Workshop - Drawing yourself as a leader

- speaking/index.md
updates speaking portion to give more recent information.
> Update speaking section

- _posts/blog/2017-09-22-memory-resources.md
- _posts/blog/2017-10-15-getting-feedback.md
- _posts/blog/2017-11-04-exploring-my-code-confidence.md
+ blog post on code confidence based on my twitter question
> Code Confidence and looking for patterns

- _posts/blog/2017-05-15-what-ive-written.md
> blog post connecting to collective idea posts

- _posts/blog/2017-12-09-git-tricks.md
> git tips blog post

- _posts/blog/2017-10-28-oss-workshop.md
adds workshop about enabling people to contribute to open source software.
> OSS workshop

- _posts/blog/2017-12-04-being-a-new-mom-in-tech.md
Old writing, but important to finally publish
> Being a new mom in tech, from 2015

- _posts/blog/2017-12-29-jquery-off-namespacing.md
A short post on a cool thing I learned
> jquery off namespacing

- _posts/blog/2019-10-04-CRDT-sources.md
PR to pull in a list of resources to link to in my conference talk.
> resources for conference talk

- speaking/index.md
Update talk to jsconf EU's baby driven development talk
> update talk sample to bdd

- _posts/blog/2020-02-03-parent-driven-development-upcoming-goals.md
what are our goals for this next year of podcasting?!
Big things.
> draft of PDD goals post

- _posts/blog/2020-07-11-planning-for-sparkles.md
- about/index.md
- speaking/index.md
- updates a posting for the new covid talk
- updates github position and speaking work
> Website updates

- _config.yml
- _layouts/post.html
- package.json
Doing some website work
- fixes errors around building locally which didn't affect the external site but made local development challenging
- updates urls to solve errors
> updates website

- _posts/blog/2022-04-18-staring-at-a-blank-page.md
- _posts/blog/2022-06-04-staring-at-a-blank-page.md
Blog post about trying to get back into blogging
> Staring at a blank page

- _posts/blog/2022-06-18-meetings-which-ones-to-consider.md
Blog post covering the different kinds of meetings and some questions about assessing meetings your team may need.
> different kinds of meetings to consider
